### PR TITLE
Set up parser for `gdc2xena`

### LINKED ISSUE #16: Improve CLI
Currently, the user requires to type `python file_name args` in order to perform CLI operations. But, when the project will be installed using `setup.py`, the files will reside at `env/site_packages`, and thus will be hard for the end-user.

It can be improved by using a single CLI command, for example, `xena-gdc-etl gdc2xena args`
and `xena-gdc-etl gdc_check_new args`. In this way, the user needs not worry about path to the python files.

See also: https://github.com/yunhailuo/xena-GDC-ETL/pull/17#issuecomment-475110147

### PR DESCRIPTION
**Pull request by ayan-b**
Closes #16 

Needs a rebase once #24 is merged.

### CODE REVIEW

**Comment by yunhailuo** [comment]
Is this on top of #24 ? If so, let's work #24 out, then rebase this PR. da4c41fe15d8cefd570b357d5f799cae6ea9aaff looks fine. But I'll take another look after #24 and rebase.

**Comment by yunhailuo** [comment]
#24 merged. Please rebase as you want.

**Comment by ayan-b** [comment]
Rebased.

**Comment by ayan-b** [comment]
The code for this PR went with the last PR itself, and the reason being the last commit I added. Thus, I am closing this PR.

**Pull request closed without merging**
