### PR TITLE
Code cleanup: Improve CLI

### PR DESCRIPTION
**Pull request by ayan-b**
- [X] `equal_matrices` (tests added)
- [X] `make_metadata` (tests added)
- [x] `merge_xena` (tests added)
- [x] `gdc_check_new`
- [ ] `gdc2xena`

Also set-up initial parser
Related to #16.

See also https://github.com/yunhailuo/xena-GDC-ETL/pull/17#issuecomment-475110147

### CODE REVIEW

**Comment by ayan-b** [comment]
Current argparser setup:
`xge xena-eql df1 df2`
Will send a commit updating the docs soon.

**Comment by yunhailuo** [comment]
Can you remind me about the overall structure/design of the CLI?

**Comment by ayan-b** [comment]
@yunhailuo, it is discussed here: https://github.com/yunhailuo/xena-GDC-ETL/issues/16#issue-421366023.

**Comment by yunhailuo** [comment]
Trying to test this PR but find a potential problem with 4c11c573b6f37ecf420bbf6b3d4f0061fa7e106a. Somehow having `xena_gdc_etl/scripts/__init__.py` prevent me from installing using `pip install ./` under a simple conda python 2.7 environment. Part of the error log:
```
  running build_scripts
  creating build/scripts-2.7
  copying and adjusting xena_gdc_etl/scripts/make_metadata.py -> build/scripts-2.7
  copying and adjusting xena_gdc_etl/scripts/gdc2xena.py -> build/scripts-2.7
  copying and adjusting xena_gdc_etl/scripts/gdc_check_new.py -> build/scripts-2.7
  copying xena_gdc_etl/scripts/equal_matrices.py -> build/scripts-2.7
  copying and adjusting xena_gdc_etl/scripts/TARGET-CCSK_phenotype_ETL.py -> build/scripts-2.7
  copying and adjusting xena_gdc_etl/scripts/panTCGA.py -> build/scripts-2.7
  warning: build_scripts: xena_gdc_etl/scripts/__init__.py is an empty file (skipping)
  
  copying and adjusting xena_gdc_etl/scripts/merge_xena.py -> build/scripts-2.7
  copying xena_gdc_etl/scripts/join_xena.sh -> build/scripts-2.7
  copying xena_gdc_etl/scripts/union_xena.sh -> build/scripts-2.7
  changing mode of build/scripts-2.7/make_metadata.py from 644 to 755
  changing mode of build/scripts-2.7/gdc2xena.py from 644 to 755
  changing mode of build/scripts-2.7/gdc_check_new.py from 644 to 755
  changing mode of build/scripts-2.7/TARGET-CCSK_phenotype_ETL.py from 644 to 755
  changing mode of build/scripts-2.7/panTCGA.py from 644 to 755
  error: [Errno 2] No such file or directory: 'build/scripts-2.7/__init__.py'
  
  ----------------------------------------
  Failed building wheel for xena-gdc-etl
  Running setup.py clean for xena-gdc-etl
Failed to build xena-gdc-etl
```

I know travis tests all pass. I'm wondering:
1. Do we test the install of the repo in travis?
2. Do you have any problems `pip install`?

**Comment by ayan-b** [comment]
During development, I use `python setup.py develop` in order to install the package. So, I have never faced the issue, thanks for pointing out.

> 1. Do we test the install of the repo in travis?
No, I will add a commit addressing this.

> 2. Do you have any problems pip install?
Yes, it turns out that the problem lies in the name of directory `scripts`. If we change the directory name to something else, `pip install` works as expected.

**Comment by ayan-b** [comment]
Ok, I will get rid of `__init__py`.

**Comment by ayan-b** [comment]
This PR is ready except for `merge_xena` and `gdc2xena` modules. They are a bit large and requires proper testing before moving into utils.

**Comment by ayan-b** [comment]
@yunhailuo, please review.

**Comment by yunhailuo** [comment]
Looks good. Thank you!

**Comment by yunhailuo** [comment]
If possible, it will be better to have commits group together. Or separate features into different PRs. @ayan-b

**Pull request merged**
