### PR TITLE
 Skip the pipeline for a datatype if the Xena Matrix is found

### PR DESCRIPTION
**Pull request by ayan-b**
I am using this in the instance. Let me know if we need it, I will add tests and docs. This is on top of #47.

### CODE REVIEW

**Comment by yunhailuo** [comment]
In general, how do you know if the existing matrix is up to date and should be skipped? If you don't rely on some checks, you decide that arbitrarily. If we decide arbitrarily, we should just use a new script to be explicit about what exact project(s) and datatype(s) we want (like `--projects` and `--datatype`). Being implicit and just relying on filename check seems lazy and unstable.

**Comment by ayan-b** [comment]
This command is kept for user convenience only and updating part is left to the user to check.

Suppose the pipeline is run and due to some errors (500 etc.), then either we can manually check or by `unfinished.json` and then execute the commands, but that would be somewhat more time-consuming.

> f we decide arbitrarily, we should just use a new script to be explicit about what exact project(s) and datatype(s) we want (like --projects and --datatype).

Avoided this since this the command will be really long.

**Comment by yunhailuo** [comment]
Is good to have a check to see what matrix is there. But I really don't think filename check is the right way to go. And it's not worth the time you saved if you are not sure the data is right. I assume retry works, no 4xx response and you don't have too many unfinished to do?

**Comment by ayan-b** [comment]
The ETL is done. Only setting the hub is left.

**Pull request closed without merging**
